spring:
  cloud:
    aws:
      credentials:
        access-key: ASIAYZKOXWE6S6BFW5NN
        secret-key: oyifsdBXho94CfyQcOJUOsrxkdCZjMsQtUdXrJJb
        session-token: IQoJb3JpZ2luX2VjEJr//////////wEaCXVzLXdlc3QtMiJIMEYCIQD+CYrS1wNBlbUdj4SdrUZKsGdog+CktUe7CJeJHLbGlAIhAJ7tODIKMygpVckA299+f9pB48LMvVZmub7Cr/Hv4d/oKqwCCGMQARoMNjA0MTQ0OTA2NTU3IgwY0VC8RQiaQyrVz9cqiQJKz8M8d+18LU+yEgCXNJPaQVsnutisVhkdl0H9zmXsvR3rZPW061zJW+YLwRfJMjvv8nalsdKosl7mq4ktR5pxqAPUIbGOybEup1MEyfEIR8REWOzCv9aCTJC7x+H7u5gLH1FBWT/p38sCVdUT65HpRHiYnZ7sfFPz53OnWOR9B/bW6tYTWWDVg5gei/YQa5Zbz/a2jkgGs/3jxGfNDn1MOM9m+waX7JtazuB4nSXU7r4Q3GrlFh/ljsVZK0DRw3E58niZTwetzcYWpyL/0tZRV6UkD6Z7MwO9bldVwkojfEn8lFLnSb9ndpoY4da93ozuG9tekQJE74NFlnf5kFTWnjuz6e66lfKCMLHdiNEGOpwBQuLCEMeV2PBqSuCfSrQGtWSlbipNoLt8cDIGRDo4LLU8He5jN05CwA7VBf4cAgRZ5xS2FumF/pznGvN+GH7zZeGXrevNRVGYQMZ2fjTGApjCzUV3JJ/cB6QesSoQVJRQQslt1yE2bkCIpkICPS5QgGufk2/V6wxuY9K0OFkvyxareri+8OzMZSc21IVNhdgoJ4G+JIQjmOqDThYZ
      region:
        static: us-east-1